cmake_minimum_required (VERSION 2.6...4.0)

project(mcpelauncher-updates LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
option(MCPELAUNCHER_UPDATES_VALIDATE "Enable Google Play validation and patch download" ON)

find_library(log-lib log)

set(protobuf_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(protobuf_BUILD_CONFORMANCE OFF CACHE BOOL "" FORCE)
set(protobuf_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(protobuf_BUILD_PROTOC_BINARIES OFF CACHE BOOL "" FORCE)
set(protobuf_BUILD_LIBPROTOC OFF CACHE BOOL "" FORCE)
set(protobuf_DISABLE_RTTI ON CACHE BOOL "" FORCE)
add_subdirectory(protobuf)
add_subdirectory(Google-Play-API)
add_library(mcpelauncher-updates SHARED src/main.cpp)
if(MCPELAUNCHER_UPDATES_VALIDATE)
  target_compile_definitions(mcpelauncher-updates PRIVATE ENABLE_VALIDATION)
endif()
target_link_libraries(mcpelauncher-updates PUBLIC libprotobuf gplayapi)
